services:
  postgres:
    image: postgres:16
    container_name: rust-crud-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust_crud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      args:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/rust_crud
    container_name: rust-crud-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rust_crud


volumes:
  postgres_data: